version: '3.3'
services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DEFAULT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEFAULT}
      - POSTGRES_DB=${POSTGRES_DB_DEFAULT}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  web:
    container_name: web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate --database=default &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout=500 --workers=3"

    restart: always
    volumes:
      - ./backend:/app/
      - static_value:/app/static_files/
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_value:/app/build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/usr/share/nginx/html/
      - static_value:/backend/static_files/
      - media_value:/backend/media/
    depends_on:
      - frontend
volumes:
  static_value:
  media_value:
  frontend_value:
  postgres_data: