# Generated by Django 3.2 on 2023-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('upc', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('images', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sort_code', models.CharField(max_length=2)),
                ('name', models.TextField()),
                ('category_level', models.SmallIntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('upc', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_message', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('is_low_stock', models.BooleanField(blank=True, null=True)),
                ('on_hand_inventory', models.IntegerField(blank=True, null=True)),
                ('limit_quantity', models.IntegerField(blank=True, null=True)),
                ('matched_manually', models.BooleanField(blank=True, null=True)),
                ('processed_by_human', models.BooleanField()),
                ('model_recognized', models.CharField(max_length=128)),
                ('is_available', models.BooleanField()),
                ('item_availability', models.CharField(max_length=19)),
                ('reclassified_by', models.CharField(max_length=1)),
                ('created_time', models.DateTimeField()),
                ('quick_product_revision_time', models.DateTimeField(blank=True, null=True)),
                ('full_product_revision_time', models.DateTimeField(blank=True, null=True)),
                ('stock_status', models.CharField(max_length=1)),
                ('breadcrumbs', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('nutritional', models.JSONField(blank=True, null=True)),
                ('specification', models.JSONField(blank=True, null=True)),
                ('brand_recognized_id', models.IntegerField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'product_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('site_url', models.TextField()),
                ('display_name', models.TextField()),
                ('is_active', models.BooleanField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.TextField()),
                ('region', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('supplier_category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier_parent_category_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_time', models.DateTimeField()),
                ('category_url', models.CharField(blank=True, max_length=512, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('matched_manually', models.BooleanField(blank=True, null=True)),
                ('processed_by_human', models.BooleanField()),
                ('category_level', models.SmallIntegerField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('dont_monitor_products', models.BooleanField()),
            ],
            options={
                'db_table': 'supplier_category',
                'managed': False,
            },
        ),
    ]
